/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: damn2605 (https://sketchfab.com/damn2605)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/bananacat-7f05042ff8854593947c94bd51b90b8a
Title: bananaCat
*/

import { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const BananaCat = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/src/assets/models/bananacat.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["bananaBones|lookAround"].play();
  }, [actions]);

  return (
    <group ref={group} {...props}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.706}
        >
          <group
            name="803f79afd410443aae291a0b5d1b1854fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="bananaBones">
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_36"
                      geometry={nodes.Object_36.geometry}
                      material={materials.heheBanana}
                      skeleton={nodes.Object_36.skeleton}
                    />
                    <group
                      name="Object_35"
                      position={[0, -35.606, 0]}
                      scale={100}
                    />
                  </group>
                </group>
                <group name="body001" position={[0, -35.606, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/src/assets/models/bananacat.glb");
export default BananaCat;
